all: ipece
	gcc -g ipece.c find_center_nonhet.c get_scored_atoms.c probe.c read_acc_atom.c read_atoms.c read_ipece_prm.c save_hist.c translate.c coor2latt.c get_rad.c strip_comment.c strip_spc.c backup_recover.c get_buried_cylinder_axis.c get_score.c rotate.c normalize_vec.c ran2.c  minimum_score_position.c back_move.c add_mem_atoms.c add_ion_atoms.c -o ipece -lm
